name: blog_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  #Functional programming in Dart and Flutter.
  fpdart: ^1.1.0
  #State Mangment
  flutter_bloc: ^8.1.6
  #di
  get_it: ^7.7.0
  #import images from phone
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.2
  #date format
  intl: ^0.19.0
  #Flutter integration for Supabase.
  supabase_flutter: ^2.6.0
  #uniuqe id
  uuid: ^4.5.0
  hive: 4.0.0-dev.2 
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
